name: Solar System Workflow

on: 
  workflow_dispatch:
  push:

env:
  TEST: ${{ secrets.TEST }}
    
jobs:
    artifact:
        name: upload artifact
        runs-on: ubuntu-latest
        environment: development
        steps:
          - name: create file
            run: |
              mkdir build
              touch build/test.txt
          - name: upload build artifact
            uses: actions/upload-artifact@v4
            with:
                name: build
                path: build
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        environment: development
        needs: artifact
        steps:
          - name: download build artifact
            uses: actions/download-artifact@v4
            with:
              name: build
          - name: print working directory
            run: ls -alh