name: Solar System Workflow

on: 
  workflow_dispatch:
  push:

env:
  KUBECONFIG: ${{ secrets.TEST }}
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: print env
          run: echo $KUBECONFIG